import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
				<main className={styles.main}>
					<Image className={styles.logo} src="/p5js.png"
						alt="logo"
						width={200}
						height={200}
						priority
					/>
					<section>
						Trying to figure out how to load p5 sound library
					</section>

					<section>
						<ul>
							<li>
								<Link href='/simplea'> Simple A </Link>
							</li>
							<li>
								<Link href='/simpleb'> Simple B </Link>
							</li>
							<li>
								<Link href='/simplec'> Simple C </Link>
							</li>
							<li>
								<Link href='/simpled'> Simple D (includes audio) </Link>
							</li>
						</ul>
					</section>
				</main>
				<footer className={styles.footer}>
					Made by Kon
				</footer>
			</div>
		</>
	);
}
